#!/usr/bin/python

from shutil import rmtree

# our imports
from rsfmri.settings import *
from rsfmri.session  import *
from rsfmri.project  import *
from rsfmri.args     import *


########################
# MAIN (program logic)
########################

if __name__ == '__main__':
    args = parse_args()

    if args.sesslist:
        # sessions from file list
        session_ids = []
        with open(args.sesslist) as f:
            for sess in f:
                if len(sess) > 1:
                    session_ids.append(sess.strip())
    else:
        # sessions from command line
        session_ids = args.session

    # create session objects
    sessions = [FCSession(s,args.sessdir) for s in session_ids]

    # initialize analysis object
    analysis = FCProject(args.label, args.output, args.sessdir, sessions)

    # overwrite output directory if specified
    if args.overwrite and os.path.isdir(analysis.dir_output):
        log.info('*********************************************')
        log.info('*** WARNING: overwriting existing results! **')
        log.info('*********************************************')
        rmtree(analysis.dir_output)

    # creates init dirs/files
    analysis.setup()

    # create seeds from coords, if necessary
    if args.coord is not None:
        for name, x, y, z in args.coord:
            seed = FCSeed(analysis.dir_seeds, name)
            seed.create(x,y,z,args.radius)
            analysis.add_seed(seed)

    if args.coordlist is not None:
        analysis.create_seeds_from_file(args.coordlist, args.radius)

    # add seeds from files
    if args.seedvol is not None:
        for name, vol in args.seedvol:
            seed = FCSeed(analysis.dir_seeds, name, vol)
            analysis.add_seed(seed)
    if args.seedvollist is not None:
        analysis.add_seeds_from_file(args.seedvollist)

    # extract timecourse signal
    analysis.extract_timecourse()

    # 1st level stats
    if args.voxelwise:
        analysis.fc_voxelwise()

    # normalize individual maps
    if args.voxelwise:
        analysis.fc_voxelwise_fisherz()

    # 2nd level stats
    if args.group_stats:
        if args.voxelwise:
            analysis.fc_voxelwise_all_groupstats(ttest=args.ttest)
        if args.matrix:
            analysis.fc_matrix_groupstats()

    analysis.generate_report()

    log.info('Completed all steps!')

