#!/usr/bin/python

from shutil import rmtree

# our imports
from rsfmri.settings import *
from rsfmri.session  import *
from rsfmri.project  import *
from rsfmri.args     import *


########################
# MAIN (program logic)
########################

if __name__ == '__main__':
    args = parse_args()

    if args.sesslist:
        # sessions from file list
        session_ids = []
        with open(args.sesslist) as f:
            for sess in f:
                if len(sess) > 1:
                    session_ids.append(sess.strip())
    else:
        # sessions from command line
        session_ids = args.session

    # create session objects
    sessions = [FCSession(s,args.sessdir) for s in session_ids]

    # initialize analysis object
    analysis = FCProject(args.label, args.output, args.sessdir, sessions)

    # overwrite output directory if specified
    if args.overwrite:
        log.info('*********************************************')
        log.info('*** WARNING: overwriting existing results! **')
        log.info('*********************************************')
        rmtree(analysis.dir_output)

    # creates init dirs/files
    analysis.setup()

    # create seeds from coords, if necessary
    if args.seed is not None:
        for name, x, y, z in args.seed:
            analysis.create_seed(name,x,y,z,args.radius)
    if args.coordlist is not None:
        analysis.create_seed_from_file(args.coordlist, args.radius)

    # add seeds from files
    if args.seedvol is not None:
        for name, vol in args.seedvol:
            analysis.add_seed(name,seedvol)
    if args.seedlist is not None:
        analysis.add_seed_from_file(args.seedlist)

    # extract timecourse signal
    analysis.extract_ts_all()

    # 1st level stats
    if args.voxelwise:
        analysis.fc_voxelwise_all()

    # no need to make 1st level matrices
    #if args.matrix:
    #    analysis.fc_matrix_all()

    # 2nd level stats
    if args.group_stats:
        if args.voxelwise:
            analysis.fc_voxelwise_groupstats()
        if args.matrix:
            analysis.fc_matrix_groupstats()

    # TODO: snapshots of rois
    analysis.generate_report()

    log.info('Completed all steps!')

