#!/usr/bin/python

import nipype.interfaces.spm as spm
import argparse
import glob
import uuid
import sys
import os

# template
scriptdir = os.path.dirname(os.path.realpath(sys.argv[0]))
mni_t2_template = os.path.join(scriptdir,'templates','SPM_EPI_TEMPLATE.nii')

# argument helper (file type)
def file_input_type(x):
    if not os.path.exists(x):
        log.error('File cannot be found: {}'.format(x))
    return os.path.abspath(x)

# print command outputs
def run_cmd(cmd_str):
    print "*"*15, "Executing", "*"*15
    print cmd_str
    print "*"*15, "Output", "*"*15
    cmd = os.popen(cmd_str)
    for line in cmd.readlines():
        print line,
    print "-" * 40

# argument parser
parser = argparse.ArgumentParser(description='normalize functional image to MNI152 2mm template')
parser.add_argument('inputfile', metavar="input.nii.gz", type=file_input_type,
                    help = 'functional input image')
parser.add_argument('outputfile', metavar="norm_output.nii.gz", type=str,
                    help = 'normalized output image')
args = parser.parse_args()

# convert input file to SPM format
tmpfile_base = str(uuid.uuid4())
tmpfile = os.path.join('/tmp', tmpfile_base)
cmd = 'mri_convert {} {} -ot spm'.format(args.inputfile, tmpfile)
run_cmd(cmd)

# spm created a file for each time-frame
tmpfiles = glob.glob('{}*img'.format(tmpfile))

# create mean image
tmpfile_mean = os.path.join('/tmp', tmpfile_base + '_mean')
#run_cmd('fslmaths {} -Tmean {}'.format(args.inputfile,tmpfile_mean))
run_cmd('fslroi {} {} 10 1'.format(args.inputfile,tmpfile_mean))

if os.path.exists(tmpfile_mean+'.nii.gz'):
    run_cmd('mri_convert {}.nii.gz {}.img -ot spm'.format(tmpfile_mean,tmpfile_mean))

# normalize 'em using SPM
norm = spm.Normalize()
norm.inputs.source = tmpfile_mean + '.img'
norm.inputs.template = mni_t2_template
norm.inputs.apply_to_files = tmpfiles
norm.inputs.write_voxel_sizes = [2,2,2]
norm.inputs.write_interp = 7
norm.inputs.write_bounding_box = [[-90,-126,-72], [90,90,108]]
norm.inputs.write_wrap = [0,1,0]
norm.run()

# grab output files
tmpfiles_output = sorted(glob.glob('/tmp/w{}???.img'.format(tmpfile_base)))

# convert outputs to single file
tmpfile_join = os.path.join('/tmp', str(uuid.uuid4()))
run_cmd('fslmerge -t {} {}'.format(tmpfile_join, ' '.join(tmpfiles_output)))

# swap L/R (thanks, SPM)
tmpfile_swap = os.path.join('/tmp', str(uuid.uuid4()))
run_cmd('fslswapdim {} -x y z {}'.format(tmpfile_join, tmpfile_swap))

# remove NaNs (thanks, SPM)
tmpfile_nan = os.path.join('/tmp', str(uuid.uuid4()))
run_cmd('fslmaths {} -nan {}'.format(tmpfile_swap, tmpfile_nan))

# modify TR
run_cmd('mri_convert -tr $(mri_info --tr {}) {} {}' \
            .format(args.inputfile,
                    tmpfile_nan+'.nii.gz',
                    args.outputfile))

############################
# clean up
############################

dafiles = [tmpfile_mean+'.nii.gz',
           tmpfile_mean+'.img',
           tmpfile_join,
           tmpfile_swap,
           'pyscript_normalize.m']

try:
    for t in tmpfiles:
        os.remove(t)
    for t in tmpfiles_output:
        os.remove(t)
    for t in dafiles:
        os.remove(t)
except: pass

print "Normalization complete!"
print " * OUTPUT: {} ".format(args.outputfile)

